name: youtube-dl
base: core18
summary: Download videos from youtube.com or other video platforms
description: |
  youtube-dl is a command-line program to download videos from YouTube.com and
  a few more sites.

adopt-info: youtube-dl
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

apps:
  youtube-dl:
    command: youtube-dl
    plugs:
      - home
      - network
      - opengl
      - removable-media
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"


parts:
  youtube-dl:
    after:
      - scriptlets
    plugin: python
    source: .
    build-packages:
      - git-core
    stage-packages:
      - ffmpeg
      - freeglut3
      - libpulse0
      - libslang2
      - libglu1-mesa
    override-pull: |
      snapcraftctl pull
      $SNAPCRAFT_STAGE/scriptlets/youtube-dl-pull

  scriptlets:
    source: snap/local/scriptlets
    plugin: dump
    organize:
      '*': scriptlets/
    prime:
      - -*

